micronaut:
  application:
    name: demo
datasources:
  customerDS:
    url: jdbc:h2:file:./DATA/devDB;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa.customerDS.properties.hibernate.hbm2ddl.auto: update
